#! /usr/bin/env bash

export VERIFY_TOKEN='mybot2018'
export PAGE_ACCESS_TOKEN='EAAD5MkK7RV4BAAktGJ1z0oc0un5dN1zkvT6f56eeyEkaExGMbA5pA2DuPJ527vOFLZB3dKSMo4pZCzfyzuAwbZAFyNldseAh5hMFyoHiaUn9xERWPI6DPd2I2CfrvDbhZCGYaBWnXK3xEH2z9eKPUops2evsF1pFLNPkeBh0oKKxGGB5wvIJ'

# Get started message
curl -X POST -H "Content-Type: application/json" -d '{
  "get_started":{
    "payload": "GET_STARTED_PAYLOAD"
  }
}' "https://graph.facebook.com/v2.6/me/messenger_profile?access_token="$PAGE_ACCESS_TOKEN

# Greeting text
curl -X POST -H "Content-Type: application/json" -d '{
  "greeting":[
    {
      "locale":"default",
      "text":"3, 2, 1... MEME IT RIP!"
    }, {
      "locale":"en_US",
      "text":"Help scientists understand today´s world through memes!"
    }
  ]
}' "https://graph.facebook.com/v2.6/me/messenger_profile?access_token="$PAGE_ACCESS_TOKEN

# Run app
python3.6 bot.py
