#! /usr/bin/env bash

export VERIFY_TOKEN='mybot'
export PAGE_ACCESS_TOKEN='EAADvKjs1ntsBAGvrcSP2OQcNTaGqUYP2evrsDFhnWCLxZCFzTI5AHbG6WsFfYvx4b0g8mlrWJl2fdZCxnmjfcD3H8qmsrgoCz1GG5ENLYolXZCD5GMS3xXPIZCRoC7UYR0bEvUBxKPgq8WvUsELQMIkYGEecnZBJva0tarCoDlZAHfcjEGaYUO'

# Get started message
curl -X POST -H "Content-Type: application/json" -d '{
  "get_started":{
    "payload": "GET_STARTED_PAYLOAD"
  }
}' "https://graph.facebook.com/v2.6/me/messenger_profile?access_token="$PAGE_ACCESS_TOKEN

# Greeting text
curl -X POST -H "Content-Type: application/json" -d '{
  "greeting":[
    {
      "locale":"default",
      "text":"3, 2, 1... MEME IT RIP!"
    }, {
      "locale":"en_US",
      "text":"Help scientists understand today´s world through memes!"
    }
  ]
}' "https://graph.facebook.com/v2.6/me/messenger_profile?access_token="$PAGE_ACCESS_TOKEN

# Run app
python3.6 bot.py
