#! /usr/bin/env bash

export VERIFY_TOKEN='mybot2018'
export PAGE_ACCESS_TOKEN='EAAGbWBf6ZCF8BABpMAPfWpW0vTdPeRaN7iibjXXyiHVw5ZAAvQgwZCgu5cAsqUfhN3eWZBFwMdhYNkqKfmZAFPkcjPWZBbOiLmh0pgPhEf55e4hH3w8SQGKxA1pwZCzwtNASs12Ugr3P6m0qJkXubN0NmjZCUkuUCOSM8idVBml9o0ZAPee9PXovc'

# Get started message
curl -X POST -H "Content-Type: application/json" -d '{
  "get_started":{
    "payload": "GET_STARTED_PAYLOAD"
  }
}' "https://graph.facebook.com/v2.6/me/messenger_profile?access_token="$PAGE_ACCESS_TOKEN

# Greeting text
curl -X POST -H "Content-Type: application/json" -d '{
  "greeting":[
    {
      "locale":"default",
      "text":"3, 2, 1... MEME IT RIP!"
    }, {
      "locale":"en_US",
      "text":"Help scientists understand today´s world through memes!"
    }
  ]
}' "https://graph.facebook.com/v2.6/me/messenger_profile?access_token="$PAGE_ACCESS_TOKEN

# Run app
python3.6 bot.py
